Import Library tensorflow

In [47]:
import tensorflow as tf

#### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [48]:
random_tensor = tf.random.normal(shape=(5, 5), mean = 2, stddev = 1, seed = 1)

random_tensor.numpy()

array([[ 2.2228835 ,  3.0766966 ,  3.635548  ,  2.2836444 ,  2.215157  ],
       [ 1.7947109 ,  3.7629523 ,  1.3837738 ,  2.6082773 ,  0.4617331 ],
       [ 1.7798336 , -0.68091345,  1.9574771 ,  2.795014  ,  1.7191308 ],
       [ 0.44874763,  1.3772097 ,  1.6113285 ,  3.164011  ,  2.0539563 ],
       [ 2.494988  ,  2.3137517 ,  2.5980914 ,  3.5366259 ,  1.1340909 ]],
      dtype=float32)

#### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [49]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

#### Tampilkan dimensi dari kedua variable tersebut

In [50]:
print('=======================================')
print('[1] Dimensi Random_Tensor : ',random_tensor.shape)
print('[2] Dimensi Prime_Tensor  : ',prime_tensor.shape)
print('=======================================')

[1] Dimensi Random_Tensor :  (5, 5)
[2] Dimensi Prime_Tensor  :  (5, 5)


#### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [60]:
print("Penjumlahan:\n\n" ,tf.add(random_tensor,prime_tensor).numpy())

Penjumlahan:

 [[  4.222883    6.0766964   8.635548    9.283645   13.215157 ]
 [ 14.794711   20.762953   20.383774   25.608276   29.461733 ]
 [ 32.779835   36.319088   42.957478   45.795013   48.71913  ]
 [ 53.448746   60.37721    62.61133    74.16401    75.053955 ]
 [ 81.49499    85.31375    91.59809   100.53663   102.134094 ]]


In [59]:
print("Pengurangan:\n\n" ,tf.subtract(random_tensor,prime_tensor).numpy())

Pengurangan:

 [[ 2.2288346e-01  7.6696634e-02 -1.3644519e+00 -4.7163553e+00
  -8.7848434e+00]
 [-1.1205289e+01 -1.3237047e+01 -1.7616226e+01 -2.0391724e+01
  -2.8538267e+01]
 [-2.9220167e+01 -3.7680912e+01 -3.9042522e+01 -4.0204987e+01
  -4.5280869e+01]
 [-5.2551254e+01 -5.7622791e+01 -5.9388672e+01 -6.7835991e+01
  -7.0946045e+01]
 [-7.6505013e+01 -8.0686249e+01 -8.6401909e+01 -9.3463371e+01
  -9.9865906e+01]]


In [58]:
print("Perkalian Matrix:\n\n" ,tf.matmul(random_tensor,prime_tensor).numpy())

Perkalian Matrix:

 [[453.17535 512.0809  555.08044 619.66174 674.9836 ]
 [270.1204  312.76617 337.40353 388.58896 430.9441 ]
 [339.33664 373.7843  399.71686 446.171   469.5013 ]
 [398.70755 441.53296 470.28195 527.9827  559.0301 ]
 [392.64392 445.7386  479.62622 543.5064  589.3708 ]]


In [61]:
print("Pembagian:\n\n" ,tf.divide(random_tensor,prime_tensor).numpy())

Pembagian:

 [[ 1.1114417   1.0255655   0.7271096   0.3262349   0.20137791]
 [ 0.13805468  0.22135013  0.0728302   0.11340337  0.01592183]
 [ 0.05741398 -0.01840307  0.04774334  0.06500033  0.03657725]
 [ 0.00846694  0.02334254  0.02641522  0.04456354  0.02813639]
 [ 0.03158212  0.02787653  0.02919204  0.03646006  0.01122862]]


In [62]:
print("Pangkat:\n\n" ,tf.pow(prime_tensor,random_tensor).numpy())

Pangkat:

 [[4.6682553e+00 2.9373611e+01 3.4764749e+02 8.5094879e+01 2.0269746e+02]
 [9.9817398e+01 4.2669801e+04 5.8817387e+01 3.5625735e+03 4.7341013e+00]
 [4.5120676e+02 8.5544161e-02 1.4354480e+03 3.6776215e+04 7.4912598e+02]
 [5.9397030e+00 2.7468472e+02 7.5292688e+02 7.2011488e+05 6.7171289e+03]
 [5.4269617e+04 2.7559428e+04 1.1606288e+05 1.0628410e+07 1.8753513e+02]]


In [63]:
print("Logaritma:\n\n" ,tf.math.log(random_tensor,prime_tensor).numpy())

Logaritma:

 [[ 0.7988052   1.1238565   1.2907599   0.8257726   0.7953233 ]
 [ 0.58484393  1.3252039   0.32481438  0.95869    -0.77276826]
 [ 0.57651985         nan  0.6716564   1.027837    0.5418188 ]
 [-0.8012946   0.32005945  0.477059    1.1518406   0.7197678 ]
 [ 0.9142839   0.8388703   0.9547771   1.2631731   0.12583137]]


#### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [65]:
print("input tensor:",random_tensor.numpy())
print('=======================================')
print("locate the maximum :", tf.reduce_max(random_tensor).numpy())
print("locate the maximum :", tf.reduce_min(random_tensor).numpy())
print('=======================================')

input tensor: [[ 2.2228835   3.0766966   3.635548    2.2836444   2.215157  ]
 [ 1.7947109   3.7629523   1.3837738   2.6082773   0.4617331 ]
 [ 1.7798336  -0.68091345  1.9574771   2.795014    1.7191308 ]
 [ 0.44874763  1.3772097   1.6113285   3.164011    2.0539563 ]
 [ 2.494988    2.3137517   2.5980914   3.5366259   1.1340909 ]]
locate the maximum : 3.7629523
locate the maximum : -0.68091345


#### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [66]:
concat = tf.concat([random_tensor,prime_tensor], axis = 1)
concat.numpy()

array([[  2.2228835 ,   3.0766966 ,   3.635548  ,   2.2836444 ,
          2.215157  ,   2.        ,   3.        ,   5.        ,
          7.        ,  11.        ],
       [  1.7947109 ,   3.7629523 ,   1.3837738 ,   2.6082773 ,
          0.4617331 ,  13.        ,  17.        ,  19.        ,
         23.        ,  29.        ],
       [  1.7798336 ,  -0.68091345,   1.9574771 ,   2.795014  ,
          1.7191308 ,  31.        ,  37.        ,  41.        ,
         43.        ,  47.        ],
       [  0.44874763,   1.3772097 ,   1.6113285 ,   3.164011  ,
          2.0539563 ,  53.        ,  59.        ,  61.        ,
         71.        ,  73.        ],
       [  2.494988  ,   2.3137517 ,   2.5980914 ,   3.5366259 ,
          1.1340909 ,  79.        ,  83.        ,  89.        ,
         97.        , 101.        ]], dtype=float32)

#### Tampilkan hasil sorting dari kedua variable di atas. (descending)

#####  Random descending

In [67]:
sort_random = tf.sort(random_tensor, direction = 'DESCENDING')
sort_random.numpy()

array([[ 3.635548  ,  3.0766966 ,  2.2836444 ,  2.2228835 ,  2.215157  ],
       [ 3.7629523 ,  2.6082773 ,  1.7947109 ,  1.3837738 ,  0.4617331 ],
       [ 2.795014  ,  1.9574771 ,  1.7798336 ,  1.7191308 , -0.68091345],
       [ 3.164011  ,  2.0539563 ,  1.6113285 ,  1.3772097 ,  0.44874763],
       [ 3.5366259 ,  2.5980914 ,  2.494988  ,  2.3137517 ,  1.1340909 ]],
      dtype=float32)

##### Prime descending

In [69]:
sort_prime = tf.sort(prime_tensor, direction = 'DESCENDING')
sort_prime.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)